%% Example diagram
graph LR
    A[Raspberrypi] -- TCP --> Main((Server))
    B[Raspberrypi] -- TCP --> Main((Server))
    C[Raspberrypi] -- TCP --> Main((Server))
    D[Raspberrypi] -- TCP --> Main((Server))
    E[Raspberrypi] -- TCP --> Main((Server))
    Main --> WebBrowser
