%% Example diagram
graph LR
    A[Raspberrypi] --> Main((Redis_DB))
    B[Raspberrypi] --> Main((Redis_DB))
    C[Raspberrypi] --> Main((Redis_DB))
    D[Raspberrypi] --> Main((Redis_DB))
    E[...] --> Main((Redis_DB))
    Main --> WebBrowser
    F((Server)) --> Main((Redis_DB))
